spring.application.name=vigilancia-docente
spring.datasource.url=jdbc:postgresql://localhost:5432/Proyecto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=P123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.cache=false

app.seed.enabled=true
