spring.application.name=vigilancia-docente
spring.datasource.url=jdbc:postgresql://localhost:5432/Proyecto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=SM01

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.seed.enabled=true
security.jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
security.jwt.expiration-hours=8
